#include "xparameters.h"
#include "xil_io.h"
#include "xil_printf.h"
#include "xil_types.h"

// AXI peripheral base address generated by Vitis
#define VIDEO_CTRL_BASE              XPAR_VIDEO_CONTROL_AXI_0_BASEADDR

// Register offsets
#define REG_CONTROL_SHADOW           0x00U
#define REG_THRESHOLD_SHADOW         0x04U
#define REG_COMMAND                  0x08U
#define REG_STATUS                   0x10U
#define REG_ACTIVE_CONFIG            0x14U
#define REG_CORE_ID                  0x1CU

// CONTROL_SHADOW mode field
#define CTRL_MODE_SHIFT              1U
#define MODE_VALUE_MASK              0x3U

// COMMAND fields
#define COMMAND_APPLY_CONFIG         0x00000001U

// STATUS fields
#define STATUS_BUSY_MASK             0x00000001U

// Video modes
#define MODE_SOBEL_MAGNITUDE         0U
#define MODE_SOBEL_THRESHOLD         1U
#define MODE_GRAYSCALE               2U
#define MODE_ORIGINAL                3U

// Default configuration
#define DEFAULT_MODE                 MODE_SOBEL_MAGNITUDE
#define DEFAULT_THRESHOLD            100U

// Expected hardware identifier
#define EXPECTED_CORE_ID             0x534F424CU

// Configuration timeout loop count
#define CONFIG_TIMEOUT               10000000U

// Threshold adjustment step
#define THRESHOLD_STEP               10U


static const char *GetModeName(u32 mode)
{
    switch (mode)
    {
        case MODE_SOBEL_MAGNITUDE:
            return "Sobel magnitude";

        case MODE_SOBEL_THRESHOLD:
            return "Thresholded Sobel";

        case MODE_GRAYSCALE:
            return "Grayscale";

        case MODE_ORIGINAL:
            return "Original";

        default:
            return "Unknown";
    }
}


static void PrintHelp(void)
{
    xil_printf("\r\n");
    xil_printf("Available commands\r\n");
    xil_printf("==================\r\n");
    xil_printf("  0  - Sobel magnitude\r\n");
    xil_printf("  1  - Thresholded Sobel\r\n");
    xil_printf("  2  - Grayscale\r\n");
    xil_printf("  3  - Original\r\n");
    xil_printf("  +  - Increase threshold by %d\r\n", THRESHOLD_STEP);
    xil_printf("  -  - Decrease threshold by %d\r\n", THRESHOLD_STEP);
    xil_printf("  s  - Show active configuration\r\n");
    xil_printf("  h  - Show this help menu\r\n");
    xil_printf("\r\n");
}


static int WaitUntilNotBusy(const char *stage)
{
    u32 status;
    u32 timeout;

    timeout = CONFIG_TIMEOUT;

    while (timeout != 0U)
    {
        status = Xil_In32(
            VIDEO_CTRL_BASE + REG_STATUS
        );

        if ((status & STATUS_BUSY_MASK) == 0U)
        {
            return 0;
        }

        timeout--;
    }

    status = Xil_In32(
        VIDEO_CTRL_BASE + REG_STATUS
    );

    xil_printf(
        "ERROR at %s: STATUS=0x%08x\r\n",
        stage,
        status
    );

    return -1;
}


static void PrintActiveConfiguration(void)
{
    u32 active_config;
    u32 active_mode;
    u32 active_threshold;

    active_config = Xil_In32(
        VIDEO_CTRL_BASE + REG_ACTIVE_CONFIG
    );

    active_mode =
        (active_config >> CTRL_MODE_SHIFT) &
        MODE_VALUE_MASK;

    active_threshold =
        (active_config >> 8U) & 0xFFU;

    xil_printf(
        "ACTIVE_CONFIG = 0x%08x\r\n",
        active_config
    );

    xil_printf(
        "Active mode = %d, %s\r\n",
        active_mode,
        GetModeName(active_mode)
    );

    xil_printf(
        "Threshold = %d\r\n",
        active_threshold
    );
}


static int SetVideoConfiguration(
    u32 requested_mode,
    u32 requested_threshold
)
{
    u32 control_value;
    u32 control_read;
    u32 threshold_read;
    u32 active_config;
    u32 active_mode;
    u32 active_threshold;

    requested_mode &=
        MODE_VALUE_MASK;

    requested_threshold &=
        0xFFU;

    // Do not start a new transaction while a previous frozen payload is still crossing clock domains. 
    if (WaitUntilNotBusy("before shadow writes") != 0)
    {
        return -1;
    }
    
    // Pack the two-bit mode into CONTROL_SHADOW bits [2:1].
    control_value =
        requested_mode << CTRL_MODE_SHIFT;

    // Write the requested configuration into the editable shadow registers.
    Xil_Out32(
        VIDEO_CTRL_BASE + REG_CONTROL_SHADOW,
        control_value
    );

    Xil_Out32(
        VIDEO_CTRL_BASE + REG_THRESHOLD_SHADOW,
        requested_threshold
    );

    // Verify shadow-register storage.
    control_read = Xil_In32(
        VIDEO_CTRL_BASE + REG_CONTROL_SHADOW
    );

    threshold_read = Xil_In32(
        VIDEO_CTRL_BASE + REG_THRESHOLD_SHADOW
    );

    if (control_read != control_value)
    {
        xil_printf(
            "ERROR: CONTROL_SHADOW mismatch\r\n"
        );

        return -1;
    }

    if ((threshold_read & 0xFFU) !=
        requested_threshold)
    {
        xil_printf(
            "ERROR: THRESHOLD_SHADOW mismatch\r\n"
        );

        return -1;
    }

    // Generate one APPLY_CONFIG command event.
    Xil_Out32(
        VIDEO_CTRL_BASE + REG_COMMAND,
        COMMAND_APPLY_CONFIG
    );

    // Wait for request CDC, pending capture, SOF commit, acknowledgement CDC, and busy clear.
    if (WaitUntilNotBusy("after APPLY") != 0)
    {
        xil_printf(
            "The requested configuration was not acknowledged.\r\n"
        );

        return -1;
    }

    // Verify the last acknowledged active configuration.
    active_config = Xil_In32(
        VIDEO_CTRL_BASE + REG_ACTIVE_CONFIG
    );

    active_mode =
        (active_config >> CTRL_MODE_SHIFT) &
        MODE_VALUE_MASK;

    active_threshold =
        (active_config >> 8U) & 0xFFU;

    if (active_mode != requested_mode)
    {
        xil_printf(
            "ERROR: active mode mismatch\r\n"
        );

        return -1;
    }

    if (active_threshold != requested_threshold)
    {
        xil_printf(
            "ERROR: active threshold mismatch\r\n"
        );

        return -1;
    }

    xil_printf(
        "Applied: mode=%d (%s), threshold=%d\r\n",
        active_mode,
        GetModeName(active_mode),
        active_threshold
    );

    return 0;
}


int main(void)
{
    u32 core_id;
    u32 current_mode;
    u32 current_threshold;
    char command;

    xil_printf("\r\n");
    xil_printf("Interactive PS video control\r\n");
    xil_printf("============================\r\n");

    xil_printf(
        "VIDEO_CTRL_BASE = 0x%08x\r\n",
        VIDEO_CTRL_BASE
    );

    // Confirm that the expected custom peripheral is present.
    core_id = Xil_In32(
        VIDEO_CTRL_BASE + REG_CORE_ID
    );

    xil_printf(
        "CORE_ID         = 0x%08x\r\n",
        core_id
    );

    if (core_id != EXPECTED_CORE_ID)
    {
        xil_printf(
            "ERROR: expected CORE_ID 0x%08x\r\n",
            EXPECTED_CORE_ID
        );

        while (1)
        {
        }
    }

    xil_printf("CORE_ID test: PASS\r\n");

    current_mode = DEFAULT_MODE;
    current_threshold = DEFAULT_THRESHOLD;
    
    xil_printf(
        "Software defaults: mode=%d, threshold=%d\r\n",
        current_mode,
        current_threshold);
    
    PrintHelp();
    PrintActiveConfiguration();

    xil_printf("\r\nCommand: ");

    while (1)
    {
        // inbyte() blocks until one character is received through the UART configured as BSP stdin.
        command = inbyte();

        // Echo the typed character because PuTTY local echo may be disabled.
        xil_printf("%c\r\n", command);

        switch (command)
        {
            case '0':
                current_mode =
                    MODE_SOBEL_MAGNITUDE;

                if (SetVideoConfiguration(
                        current_mode,
                        current_threshold
                    ) != 0)
                {
                    xil_printf(
                        "Mode update failed\r\n"
                    );
                }
                break;

            case '1':
                current_mode =
                    MODE_SOBEL_THRESHOLD;

                if (SetVideoConfiguration(
                        current_mode,
                        current_threshold
                    ) != 0)
                {
                    xil_printf(
                        "Mode update failed\r\n"
                    );
                }
                break;

            case '2':
                current_mode =
                    MODE_GRAYSCALE;

                if (SetVideoConfiguration(
                        current_mode,
                        current_threshold
                    ) != 0)
                {
                    xil_printf(
                        "Mode update failed\r\n"
                    );
                }
                break;

            case '3':
                current_mode =
                    MODE_ORIGINAL;

                if (SetVideoConfiguration(
                        current_mode,
                        current_threshold
                    ) != 0)
                {
                    xil_printf(
                        "Mode update failed\r\n"
                    );
                }
                break;

            case '+':
                if (current_threshold <=
                    (255U - THRESHOLD_STEP))
                {
                    current_threshold +=
                        THRESHOLD_STEP;
                }
                else
                {
                    current_threshold = 255U;
                }

                if (SetVideoConfiguration(
                        current_mode,
                        current_threshold
                    ) != 0)
                {
                    xil_printf(
                        "Threshold update failed\r\n"
                    );
                }
                break;

            case '-':
                if (current_threshold >=
                    THRESHOLD_STEP)
                {
                    current_threshold -=
                        THRESHOLD_STEP;
                }
                else
                {
                    current_threshold = 0U;
                }

                if (SetVideoConfiguration(
                        current_mode,
                        current_threshold
                    ) != 0)
                {
                    xil_printf(
                        "Threshold update failed\r\n"
                    );
                }
                break;

            case 's':
            case 'S':
                PrintActiveConfiguration();
                break;

            case 'h':
            case 'H':
            case '?':
                PrintHelp();
                break;

            case '\r':
            case '\n':
                break;

            default:
                xil_printf(
                    "Unknown command '%c'. Press h for help.\r\n",
                    command
                );
                break;
        }

        xil_printf("Command: ");
    }

    return 0;
}